// ============================================================================
// SiteFooter — sticky-bottom, site-wide disclaimer (not per-report).
//
// The disclaimer lives here once, not repeated on every report. The footer
// sticks to the bottom of the viewport when content is short and is pushed
// down naturally when content is long (handled by the root layout flex column).
// ============================================================================

export function SiteFooter() {
  return (
    <footer className="mt-auto border-t border-wire bg-paper">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base font-semibold text-ink">
              Verdikt
            </span>
            <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-ink-mute">
              v0.1 · portfolio build
            </span>
          </div>

          <p className="text-[11.5px] leading-relaxed text-ink-mute max-w-xl">
            Verdikt is a research and demonstration project. Reports are
            generated by AI agents from public data and are{" "}
            <strong className="text-ink-soft">not investment advice</strong>.
            Verify any figure against primary sources before acting.
          </p>
        </div>
      </div>
    </footer>
  );
}
