import re
import json

PROHIBITED_COMPLIANCE_PATTERNS = [
    (r"\b100%\s+risk\s+free\b", "low-risk profile"),
    (r"\bguaranteed\s+profit\b", "potential upside"),
    (r"\bzero\s+risk\b", "managed risk profile"),
    (r"\bcannot\s+lose\s+money\b", "carries market risks"),
    (r"\bguaranteed\s+returns?\b", "projected returns"),
    (r"\briskless\s+investment\b", "investment opportunity"),
]

VALID_SIGNALS = ["Buy", "Hold", "Sell", "Accumulate", "Watch"]

FINANCIAL_DISCLAIMER_TEXT = (
    "DISCLAIMER: This report is generated by an automated multi-agent AI system for "
    "educational and due diligence research purposes only. It does NOT constitute financial, "
    "investment, legal, or tax advice. Past performance is not indicative of future results. "
    "Always consult a licensed financial advisor before making investment decisions."
)

def sanitize_compliance_claims(text: str) -> str:
    """
    Scans LLM output text for non-compliant financial claims (e.g. guaranteed profits)
    and replaces them with compliant risk-aware language.
    """
    if not text:
        return text

    sanitized = text
    for pattern, replacement in PROHIBITED_COMPLIANCE_PATTERNS:
        sanitized = re.sub(pattern, replacement, sanitized, flags=re.IGNORECASE)

    return sanitized

def clean_json_output(raw_text: str) -> str:
    """
    Strips Markdown code block formatting (```json ... ```) and leading/trailing
    conversational text to extract clean JSON strings.
    """
    if not raw_text:
        return "{}"

    text = raw_text.strip()
    
    # Strip markdown block fences
    if text.startswith("```"):
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    # Extract JSON object between first { and last }
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and start < end:
        return text[start:end+1]

    return text

def validate_verdict_taxonomy(verdict: dict) -> dict:
    """
    Ensures verdict signal is strictly within allowed taxonomy and confidence is bounded [0, 100].
    """
    if not isinstance(verdict, dict):
        verdict = {}

    raw_signal = str(verdict.get("signal", "Hold")).strip()
    
    # Standardize signal
    matched_signal = "Hold"
    for valid in VALID_SIGNALS:
        if valid.lower() in raw_signal.lower():
            matched_signal = valid
            break
    
    verdict["signal"] = matched_signal

    # Clamp confidence
    try:
        conf = float(verdict.get("confidence", 50))
        verdict["confidence"] = int(max(0, min(100, conf)))
    except Exception:
        verdict["confidence"] = 50

    # Sanitize text fields
    verdict["headline"] = sanitize_compliance_claims(str(verdict.get("headline", "Analysis complete.")))
    verdict["reasoning"] = sanitize_compliance_claims(str(verdict.get("reasoning", "")))

    return verdict

def apply_output_guardrails(report: dict) -> dict:
    """
    Applies regulatory disclaimers, compliance filters, and verdict validations to the final report payload.
    """
    if not isinstance(report, dict):
        return report

    # 1. Enforce Disclaimer
    report["disclaimer"] = FINANCIAL_DISCLAIMER_TEXT

    # 2. Validate & Sanitize Verdict
    if "verdict" in report:
        report["verdict"] = validate_verdict_taxonomy(report["verdict"])

    # 3. Sanitize Synthesis Paragraphs
    if "synthesis" in report and "paragraphs" in report["synthesis"]:
        sanitized_paras = []
        for p in report["synthesis"]["paragraphs"]:
            sanitized_paras.append(sanitize_compliance_claims(str(p)))
        report["synthesis"]["paragraphs"] = sanitized_paras

    return report
